apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wksp-user1-dev

resources:
  - ../../base
  - configmap.yaml

images:
  - name: ai-agent
    newName: image-registry.openshift-image-registry.svc:5000/wksp-user1-dev/ai-agent
    digest: sha256:185a0310638983cdf69eaf81d395097a3c5103fcc934541d88052af553633a4d
