apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wksp-user1-dev

resources:
  - ../../base
  - configmap.yaml

images:
  - name: ai-agent
    newName: image-registry.openshift-image-registry.svc:5000/wksp-user1-dev/ai-agent
    digest: sha256:89bdf7046a119665dbc7828796544b42259d8bf34d2d2a9ce10d05711d1fd892
