apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wksp-user1-dev

resources:
  - ../../base
  - configmap.yaml

images:
  - name: ai-agent
    newName: image-registry.openshift-image-registry.svc:5000/wksp-user1-dev/ai-agent
    digest: sha256:385d7156686a9ca2f0473553bfda3e1d5cbd1a989b177400735158bbc2e8e6d1
