apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-agent-config
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/part-of: openshift-ai-agent
    app.kubernetes.io/environment: prod
data:
  LLAMA_STACK_URL: "http://agent-llama-stack-service.wksp-user1.svc.cluster.local:8321"
  MODEL_NAME: "maas-vllm-inference-1/qwen3-4b-instruct"
  KUBERNETES_MCP_URL: "http://ocp-mcp-server.lls-demo.svc.cluster.local:8080/mcp"
  SLACK_MCP_URL: "http://slack-mcp-server.lls-demo.svc.cluster.local/mcp"
