apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-eventlistener
  namespace: wksp-user1-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-agent-eventlistener-binding
  namespace: wksp-user1-cicd
subjects:
  - kind: ServiceAccount
    name: ai-agent-eventlistener
    namespace: wksp-user1-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wksp-user1-cicd-ai-agent-eventlistener
subjects:
  - kind: ServiceAccount
    name: ai-agent-eventlistener
    namespace: wksp-user1-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
