apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-agent
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/part-of: openshift-ai-agent
spec:
  to:
    kind: Service
    name: ai-agent
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
